# Generated by Django 5.0 on 2024-01-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0013_agentbigtimebundleprice_bigtimebundleprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='afa_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
