# Generated by Django 4.2.4 on 2024-05-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0015_announcement_afaregistration_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_price_total', models.FloatField()),
                ('purchase_price_total', models.FloatField()),
                ('profit', models.FloatField()),
                ('date_and_time', models.DateTimeField(auto_now_add=True)),
                ('channel', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='bigtimebundleprice',
            name='purchase_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='isharebundleprice',
            name='purchase_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mtnbundleprice',
            name='purchase_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mtntransaction',
            name='transaction_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='topuprequest',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
