# Generated by Django 5.0 on 2024-05-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0018_agentatcreditprice_agentvodabundleprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAgentATCreditPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('minutes', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SuperAgentVodaBundlePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('bundle_volume', models.FloatField()),
            ],
        ),
    ]
