# Generated by Django 5.1a1 on 2024-06-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0020_agentvodabundleprice_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininfo',
            name='active_payment',
            field=models.CharField(blank=True, choices=[('Direct', 'Direct'), ('Paystack', 'Paystack'), ('AppsNMobile', 'AppsNMobile')], max_length=250, null=True),
        ),
    ]
