# Generated by Django 5.1a1 on 2024-06-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0022_alter_admininfo_active_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininfo',
            name='active_payment',
            field=models.CharField(choices=[('MTN Mobile Money', 'MTN Mobile Money'), ('Vodafone Cash', 'Vodafone Cash'), ('AT Money', 'AT Money')], default='AppsNMobile', max_length=250),
        ),
    ]
