# Generated by Django 5.1a1 on 2024-06-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0023_alter_admininfo_active_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admininfo',
            name='active_payment',
            field=models.CharField(choices=[('Direct', 'Direct'), ('Paystack', 'Paystack'), ('AppsNMobile', 'AppsNMobile')], default='AppsNMobile', max_length=250),
        ),
    ]
